apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo
  name: hera
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "patch" ]
- apiGroups: [""] # "" indicates the core API group
  resources: ["workflows.argoproj.io"]
  verbs: ["get", "watch", "list", "create", "patch" ]
